In [1]:
%%HTML
<h2 align="center" style="color: red;"> Linear regression with multiple variables </h2>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

## Before applying any ML model you should preprocess data i.e., here you can see that there is NaN in the bedrooms column, so it must be filled before going into analysis 

## So to fill it, median of bedrooms column will be best value. Let's calculate median of bedrooms, for getting integer value, import math module

In [3]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

### Now fill NaN with median , use fillna() method, and change the original df

In [4]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

## Now create a linear regression object

In [6]:
reg = linear_model.LinearRegression()
reg

LinearRegression()

In [8]:
# reg.fit(training data,  target data)
# here area, bedrooms, age are training data and price is target data, so w'll write that
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

## Now our model is ready

### these are coefficients of linear regression equation 
### price = m1*area  +  m2*bedrooms  +  m3*age  +  b
### m1,m2,m3 are coefficients and b is intercept

In [9]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [10]:
reg.intercept_

383724.99999999994

### Now we can predict the price of a home with given area, bedrooms and age 

### Let's predict for 3000 sqr ft area, 3 bedrooms, 40 year old home
### And 2500 sqr ft area, 4 bedrooms, 5 year oold home

In [11]:
reg.predict([[3000,3,40]])

C:\Users\CHARMEE\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [12]:
reg.predict([[2500,4,5]])

C:\Users\CHARMEE\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])