In [2]:
%%HTML
<h2 align="center" style="color:red;"> Predicting Salary Assignment </h2>
<h3 align="center" style="color:blue;"> Linear regression with multiple Variables </h3>

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import math

In [24]:
df = pd.read_csv("hiring.csv")
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

## Let's first fill the NaN values with Zero in the Experience column

In [25]:
df.experience = df.experience.fillna("zero")
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

## now the experience column data are in strings, so we need to convert them into numbers, for that install word2number module.

In [7]:
%%cmd
pip install word2number

Microsoft Windows [Version 10.0.19043.1826]
(c) Microsoft Corporation. All rights reserved.

D:\PYTHON>pip install word2number
Defaulting to user installation because normal site-packages is not writeable
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Using legacy 'setup.py install' for word2number, since package 'wheel' is not installed.
  Running setup.py install for word2number: started
  Running setup.py install for word2number: finished with status 'done'


You should consider upgrading via the 'C:\Program Files\Python310\python.exe -m pip install --upgrade pip' command.



D:\PYTHON>

In [8]:
from word2number import w2n

## using w2n for converting word to number

In [26]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

## Filling the NaN values in test_cores column with the median of rest of the score values

In [23]:
mean = math.floor(df.test_score.mean())
mean

7

In [27]:
df.test_score = df.test_score.fillna(math.floor(df.test_score.mean()))
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         7.0                7   72000
7          11         7.0                8   80000

## Our data frame is processed well, Now creating a linear regression object

In [28]:
reg = linear_model.LinearRegression()
reg

LinearRegression()

## Now training our ML model with training data , for that making a reg.fit

In [29]:
reg.fit(df[['experience','test_score','interview_score']],df[['salary']])

LinearRegression()

## model is ready, now let's do prediction

In [30]:
reg.predict([[4,7,9]])

C:\Users\CHARMEE\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[61558.23430121]])

In [31]:
reg.predict([[0,9,9]])

C:\Users\CHARMEE\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[54311.7764403]])

In [32]:
reg.coef_

array([[2922.26901502, 2221.30909959, 2147.48256637]])

In [34]:
reg.intercept_

array([14992.65144669])

In [35]:
reg.predict([[2,9,6]])

C:\Users\CHARMEE\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[53713.86677124]])

In [36]:
reg.predict([[12,10,10]])

C:\Users\CHARMEE\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[93747.79628651]])